# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Squashed migration: full final schema of django_checkout, replacing the historical chain
# 0001..0083. Data operations from the old chain (0044 suppliers-from-channels backfill,
# 0049 shipping-price-matrix schema conversion, 0058 FK->M2M conversion, 0073 order
# emails/used-coupons backfill) transform rows that cannot exist on a fresh database and are
# intentionally omitted as no-ops.
# Generated by Django 6.0.7 on 2026-07-11 19:53

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models

import django_checkout.models.order_attachment


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_checkout", "0001_initial"),
        ("django_checkout", "0002_paymentintent_external_order_id_and_more"),
        ("django_checkout", "0003_deliverypoint_created_deliverypoint_deleted_and_more"),
        ("django_checkout", "0004_remove_customer_billing_address_and_more"),
        ("django_checkout", "0005_alter_paymentmethod_provider"),
        ("django_checkout", "0006_shippingoption_tax_rate_alter_stock_product"),
        ("django_checkout", "0007_alter_stock_product"),
        ("django_checkout", "0008_shippingoption_new_price"),
        ("django_checkout", "0009_item_name"),
        ("django_checkout", "0010_paymentintent_payu_response"),
        ("django_checkout", "0011_alter_order_order_status_and_more"),
        ("django_checkout", "0012_alter_productrepresentation_unique_together_and_more"),
        ("django_checkout", "0013_discountrulecode_is_omnibus"),
        ("django_checkout", "0014_paymentmethod_fee_type_paymentmethod_fee_value"),
        ("django_checkout", "0015_orderattachment"),
        ("django_checkout", "0016_paymentmethod_currencies"),
        ("django_checkout", "0017_channel_min_order_price"),
        ("django_checkout", "0018_shippingmethod_max_weight_limitedproducts"),
        ("django_checkout", "0019_alter_order_order_status_and_more"),
        ("django_checkout", "0020_shippingmethod_price_type_shippingpricebyweight"),
        ("django_checkout", "0021_alter_paymentintent_payment_status_and_more"),
        ("django_checkout", "0022_shippingoptionmodifier_and_more"),
        ("django_checkout", "0023_discountmodeofaction_and_more"),
        ("django_checkout", "0024_alter_discountrulecode_modifier_and_more"),
        ("django_checkout", "0025_alter_orderattachment_attachment"),
        ("django_checkout", "0026_discountmodeofaction_features_qty_greater_than_attr_value_and_more"),
        ("django_checkout", "0027_channel_discount_apply_type"),
        ("django_checkout", "0028_alter_channel_min_order_price"),
        ("django_checkout", "0029_cart_original_cart_channel_default_attr_split_and_more"),
        ("django_checkout", "0030_channel_default_attr_split_payment_fee_and_more"),
        ("django_checkout", "0031_alter_paymentmethod_provider"),
        ("django_checkout", "0032_shippingintent_and_more"),
        ("django_checkout", "0033_channel_split_order_mechanism_and_more"),
        ("django_checkout", "0034_alter_paymentmethod_provider"),
        ("django_checkout", "0035_alter_limitedproducts_options_and_more"),
        ("django_checkout", "0036_channel_order_pretty_id_prefix"),
        ("django_checkout", "0037_alter_paymentmethod_provider"),
        ("django_checkout", "0038_stock_saleable_quantity_limit_per_order"),
        ("django_checkout", "0039_order_extra"),
        ("django_checkout", "0040_channel_discount_mode_of_action_price_restriction_type"),
        ("django_checkout", "0041_discountmodeofaction_features_qty_is_multiple_of_attr_value"),
        ("django_checkout", "0042_alter_shippingmethod_method_type"),
        ("django_checkout", "0043_invoice"),
        ("django_checkout", "0044_supplier_alter_stock_product_suppliercustomer_and_more"),
        ("django_checkout", "0045_alter_channel_split_order_mechanism_and_more"),
        ("django_checkout", "0046_remove_shippingoption_has_country_or_avaliable_for_all_and_more"),
        ("django_checkout", "0047_discountcode_max_uses_per_user_and_more"),
        ("django_checkout", "0048_discountcustomermodeofaction"),
        ("django_checkout", "0049_shippingpricematrix_and_more"),
        ("django_checkout", "0050_alter_paymentmethod_provider"),
        ("django_checkout", "0051_alter_splitorderlink_options_and_more"),
        ("django_checkout", "0052_alter_shippingmethod_method_type"),
        ("django_checkout", "0053_saleoffer_saleofferprice_and_more"),
        ("django_checkout", "0054_linkedproducts_alter_limitedproducts_options_and_more"),
        ("django_checkout", "0055_alter_splitorderlink_split_by_attribute_value"),
        ("django_checkout", "0056_alter_limitedproducts_unique_together_and_more"),
        ("django_checkout", "0057_alter_discountrulecode_modifier"),
        ("django_checkout", "0058_remove_discountcode_code_unique_per_channel_and_more"),
        ("django_checkout", "0059_paymentmethod_position_shippingmethod_dpm_code_and_more"),
        ("django_checkout", "0060_remove_limitedproducts_limited_product_check_and_more"),
        ("django_checkout", "0061_channel_feature_separate_to_other_order"),
        ("django_checkout", "0062_alter_paymentmethod_provider"),
        ("django_checkout", "0063_alter_limitedproducts_association_type_and_more"),
        ("django_checkout", "0064_channel_pretty_id_is_random_right_part_and_more"),
        ("django_checkout", "0065_paymentmethod_customer_group_and_more"),
        ("django_checkout", "0066_channel_show_product_prices_when_invalid"),
        ("django_checkout", "0067_alter_paymentmethod_provider"),
        ("django_checkout", "0068_channel_preorder_date_feature_idx_and_more"),
        ("django_checkout", "0069_alter_discountrulecode_modifier_and_more"),
        ("django_checkout", "0070_apiadminkey"),
        ("django_checkout", "0071_alter_shippingoption_tax_rate"),
        ("django_checkout", "0072_thresholdproductfilter_gratisproductfilter_and_more"),
        ("django_checkout", "0073_usedcoupon_order_billing_email_order_shipping_email_and_more"),
        ("django_checkout", "0074_alter_usedcoupon_billing_email_and_more"),
        ("django_checkout", "0075_discountrulecode_extension"),
        ("django_checkout", "0076_alter_order_customer"),
        ("django_checkout", "0077_discountrulecode_show_when_invalid"),
        ("django_checkout", "0078_discountrulecode_currencies_and_more"),
        ("django_checkout", "0079_customsthresholdconfig"),
        ("django_checkout", "0080_customsthresholdconfig_apply_threshold_to_shipping"),
        ("django_checkout", "0081_delete_deliverypoint"),
        ("django_checkout", "0081_shippingmethod_max_volume"),
        ("django_checkout", "0082_merge_20260609_1038"),
        ("django_checkout", "0083_remove_paymentintent_one_intent_per_order_and_more"),
    ]

    dependencies = [
        ("django_accounts", "0001_squashed_0032_customer_indexes"),
        ("django_pim", "0001_squashed_0060_productattribute_nulls_not_distinct"),
        # Manually pinned to the migration that creates the FK-target tables. makemigrations
        # points at the latest regional migration (0002_reset_pk_sequences), which existing
        # databases may not have applied yet — that would raise InconsistentMigrationHistory
        # once this squash is marked applied via `replaces`.
        ("django_regional", "0001_squashed_0006_country_default_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("label", models.CharField(default="", max_length=128, unique=True)),
                (
                    "discount_mode_of_action_price_restriction_type",
                    models.CharField(
                        choices=[("brutto", "Brutto"), ("netto", "Netto")],
                        default="brutto",
                        help_text="Declare if the price restriction for discount mode of action is netto or brutto",
                        max_length=256,
                    ),
                ),
                ("order_pretty_id_prefix", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "pretty_id_is_random_right_part",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the right part of the pretty ID will be random. If False, it will be sequential.",
                    ),
                ),
                ("feature_idxs_for_split_order", models.CharField(blank=True, max_length=256)),
                (
                    "default_attr_split",
                    models.CharField(
                        blank=True,
                        help_text="Default attribute idx for split order, if this field = None - product without attribute will be split to separate order",
                        max_length=256,
                    ),
                ),
                (
                    "force_splitting_order_in_checkout",
                    models.BooleanField(
                        default=False,
                        help_text="Force splitting order in checkout. If False order will be split only if it will be declared in cart by customer.",
                    ),
                ),
                (
                    "split_order_shipping_cost_mechanism",
                    models.CharField(
                        choices=[
                            (
                                "attribute_based_shipping_cost_assignment",
                                "Assigning the delivery cost to the split order with the specified attribute provided in the 'default_attr_split_shipping' field.",
                            ),
                            (
                                "shipping_cost_equally_divided",
                                "Divides the shipping cost equally among all orders. Any potential rounding discrepancies will be added to the first one in the sequence.",
                            ),
                        ],
                        default="attribute_based_shipping_cost_assignment",
                        help_text="Mechanism for split order shipping cost assignment",
                        max_length=1024,
                    ),
                ),
                (
                    "default_attr_split_shipping",
                    models.CharField(
                        blank=True, help_text="Assign a shipping cost to an order with this attribute", max_length=256
                    ),
                ),
                (
                    "split_order_payment_fee_mechanism",
                    models.CharField(
                        choices=[
                            (
                                "attribute_based_payment_fee_assignment",
                                "Assigning the payment fee to the split order with the specified attribute provided in the 'default_attr_payment_fee' field.",
                            ),
                            (
                                "payment_fee_equally_divided",
                                "Divides the payment fee equally among all orders. Any potential rounding discrepancies will be added to the first one in the sequence.",
                            ),
                        ],
                        default="attribute_based_payment_fee_assignment",
                        help_text="Mechanism for split order payment_fee assignment",
                        max_length=1024,
                    ),
                ),
                (
                    "default_attr_split_payment_fee",
                    models.CharField(
                        blank=True, help_text="Assign a payment fee to an order with this attribute", max_length=256
                    ),
                ),
                (
                    "min_order_price",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "discount_apply_type",
                    models.CharField(
                        choices=[
                            ("before", "Add discount before tax applied. Discount from price net."),
                            ("after", "Add discount after tax applied. Discount from price gross."),
                        ],
                        default="after",
                        max_length=10,
                    ),
                ),
                (
                    "split_order_mechanism",
                    models.CharField(
                        choices=[("MODIFY_AND_CREATE", "Modify original order and create new needed orders")],
                        default="MODIFY_AND_CREATE",
                        max_length=45,
                    ),
                ),
                (
                    "feature_separate_to_other_order",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Declare which features should be separated to other order. Example: ['feature1', 'feature2']",
                    ),
                ),
                ("preorder_feature_idx", models.CharField(blank=True, max_length=256)),
                ("preorder_feature_value", models.CharField(blank=True, max_length=256)),
                ("preorder_date_feature_idx", models.CharField(blank=True, max_length=256)),
                (
                    "show_product_prices_when_invalid",
                    models.BooleanField(
                        default=False,
                        help_text="Show product prices when they are invalid. If False, invalid prices will be hidden.",
                    ),
                ),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True, related_name="channels", to="django_regional.country", verbose_name="countries"
                    ),
                ),
                (
                    "currencies",
                    models.ManyToManyField(
                        blank=True, related_name="channels", to="django_regional.currency", verbose_name="currencies"
                    ),
                ),
                (
                    "default_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_channels",
                        to="django_regional.country",
                        verbose_name="default_country",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_channels",
                        to="django_regional.currency",
                        verbose_name="default_currency",
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_channels",
                        to="django_regional.language",
                        verbose_name="default_language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True, related_name="channels", to="django_regional.language", verbose_name="languages"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "channels",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cart_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "cart_status",
                    models.CharField(
                        choices=[("new", "New"), ("confirmed", "Confirmed"), ("closed", "Closed")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("in_status_since", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("cart_body", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_accounts.customer"
                    ),
                ),
                (
                    "original_cart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="og_splitted_orders",
                        to="django_checkout.cart",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_checkout.channel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIAdminKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(editable=False, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomsThresholdConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-item threshold in threshold_currency, e.g. 3000 (NOK).",
                        max_digits=12,
                    ),
                ),
                (
                    "channel_to_threshold_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="How many threshold currency units equal 1 channel currency unit. E.g. EUR channel with NOK threshold: 11.24 (1 EUR = 11.24 NOK). Update monthly when exchange rate changes.",
                        max_digits=14,
                    ),
                ),
                (
                    "scheme_code",
                    models.CharField(
                        help_text="Scheme name shown to frontend, e.g. 'VOEC', 'GST', 'IOSS'.", max_length=20
                    ),
                ),
                (
                    "scheme_number",
                    models.CharField(
                        blank=True, help_text="Scheme registration number, e.g. 'NO12345VOEC'.", max_length=64
                    ),
                ),
                (
                    "apply_threshold_to_shipping",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, shipping and payment fee VAT follows the threshold scenario: BELOW_THRESHOLD → standard tax rate; ABOVE_THRESHOLD → 0% VAT.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Delivery country, e.g. Norway.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_regional.country",
                    ),
                ),
                (
                    "threshold_currency",
                    models.ForeignKey(
                        help_text="Currency of the threshold value, e.g. NOK.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_regional.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customs Threshold Config",
                "verbose_name_plural": "Customs Threshold Configs",
            },
        ),
        migrations.CreateModel(
            name="DiscountModeOfAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("take_common_part", models.BooleanField(default=False)),
                ("product_price_to", models.PositiveIntegerField(blank=True, null=True)),
                ("product_price_from", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_price_to", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_price_from", models.PositiveIntegerField(blank=True, null=True)),
                ("qty_to", models.PositiveIntegerField(blank=True, null=True)),
                ("qty_from", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_qty_to", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_qty_from", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_inclusion_or_exclusion",
                    models.CharField(
                        choices=[
                            ("inclusion", "Includes all products with specific parameters."),
                            ("exclusion", "Excludes all products with specific parameters."),
                        ],
                        default="inclusion",
                        max_length=256,
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(blank=True, related_name="%(class)s_attributes", to="django_pim.attribute"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_categories", to="django_pim.productcategory"
                    ),
                ),
                (
                    "features_qty_greater_than_attr_value",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Include or exclude product which have product attribute associated with the given feature and if the quantity of the product in the cart exceeds the value of this attribute.",
                        related_name="%(class)s_features_qty_greater_than_attr_value",
                        to="django_pim.feature",
                    ),
                ),
                (
                    "features_qty_is_multiple_of_attr_value",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Include or exclude product which have product attribute associated with the given feature and if the quantity of the product in the cart is a multiple of the value of this attribute.",
                        related_name="%(class)s_features_qty_is_multiple_of_attr_value",
                        to="django_pim.feature",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If you pick product configurable all child will be excluded/included",
                        related_name="%(class)s_products",
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GratisProductFilter",
            fields=[],
            options={
                "ordering": ["-id"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_checkout.discountmodeofaction",),
        ),
        migrations.CreateModel(
            name="DiscountRuleCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "free_shipping",
                    models.BooleanField(default=False, help_text="Czy rola koszykowa ma powodować darmową dostawę."),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.0",
                        help_text="Minimalna wartość koszyka, dla którego zadziała rola koszykowa",
                        max_digits=12,
                    ),
                ),
                (
                    "free_order",
                    models.BooleanField(default=False, help_text="Czy rola koszykowa ma powodować darmowe zamówienie."),
                ),
                (
                    "is_omnibus",
                    models.BooleanField(
                        default=False,
                        help_text="Flaga oznacza, że reguła jest publiczna na takim poziomie, który kwalifikuje ją do przeliczeń ceny omnibus.",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("all", "Discount for everyone."),
                            ("first_order_logged", "Discount only available for logged-in users without prior orders."),
                            ("first_order_all", "Discount for all users without prior orders."),
                        ],
                        default="all",
                        max_length=256,
                    ),
                ),
                (
                    "modifier",
                    models.CharField(
                        choices=[
                            ("None", "Without discount"),
                            ("percent_discount", "Percent discount."),
                            ("price_discount", "Price discount."),
                            (
                                "step_qty_percent_discount",
                                "Progressive/step percent discount based on quantity of the product (line).",
                            ),
                            (
                                "step_qty_percent_discount_whole_cart",
                                "Progressive/step percent discount based on the sum of the quantity whole cart.",
                            ),
                            (
                                "step_qty_price_discount_whole_cart",
                                "Progressive/step price discount based on the sum of the quantity whole cart.",
                            ),
                            (
                                "step_qty_fixed_price_per_currency",
                                "Progressive/step fixed price per currency based on quantity in cart.",
                            ),
                            (
                                "step_price_percent_discount",
                                "Progressive/step price discount based on the total amount whole cart.",
                            ),
                            (
                                "cheapest_gratis",
                                "The role defining how many units of the cheapest product should be free.",
                            ),
                            (
                                "most_expensive_gratis",
                                "The role defining how many units of the most expensive product should be free.",
                            ),
                            (
                                "gratis_stepped",
                                "The role defining how many units of the gratis product should be gratis. (all product in ModeOfAction are available for gratis, will be picked by client in cart)",
                            ),
                            (
                                "gratis_by_sku_in_cart",
                                "The role allowing gratis, but only when all sku in extra_value are in cart (all product in ModeOfAction are available for gratis, will be picked by client in cart)",
                            ),
                        ],
                        default="None",
                        max_length=256,
                    ),
                ),
                ("extra_value", models.JSONField(default=dict)),
                (
                    "extension",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dodatkowe dane w formacie JSON (np. custom copy, opisy, teksty marketingowe).",
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("combine_with_other_rules", models.BooleanField(default=False)),
                ("automatic_applications", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True, help_text="Czy reguła rabatowa jest aktywna.")),
                (
                    "show_when_invalid",
                    models.BooleanField(
                        default=True,
                        help_text="Czy reguła gratisowa ma być widoczna w /gratis-rules/ nawet gdy użytkownik nie spełnia warunków.",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "channels",
                    models.ManyToManyField(related_name="discount_rule_code_channels", to="django_checkout.channel"),
                ),
                (
                    "currencies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Waluty, dla których reguła rabatowa jest ważna. Brak oznacza dla wszystkich.",
                        related_name="discount_rule_code_currency",
                        to="django_regional.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount Rule: Code",
                "verbose_name_plural": "Discount Rules: Code",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="discountmodeofaction",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_mode_of_actions_rule",
                to="django_checkout.discountrulecode",
            ),
        ),
        migrations.CreateModel(
            name="DiscountCustomerModeOfAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("take_common_part", models.BooleanField(default=False)),
                (
                    "is_inclusion_or_exclusion",
                    models.CharField(
                        choices=[
                            ("inclusion", "Includes all products with specific parameters."),
                            ("exclusion", "Excludes all products with specific parameters."),
                        ],
                        default="inclusion",
                        max_length=256,
                    ),
                ),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="discount_mode_of_actions_customers",
                        to="django_accounts.customer",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="discount_mode_of_actions_groups",
                        to="django_accounts.group",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_customer_mode_of_actions_rule",
                        to="django_checkout.discountrulecode",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("max_used", models.IntegerField(default=1)),
                ("max_uses_per_user", models.IntegerField(blank=True, default=None, null=True)),
                ("current_used", models.IntegerField(default=0)),
                ("active_from", models.DateField(blank=True, default=None, null=True)),
                ("active_to", models.DateField(blank=True, default=None, null=True)),
                ("max_products_qty", models.IntegerField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="django_checkout.discountrulecode",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("billing_email", models.TextField(blank=True, null=True)),
                ("shipping_email", models.TextField(blank=True, null=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("unpaid", "Unpaid"),
                            ("confirmed", "Confirmed"),
                            ("holded", "On hold"),
                            ("in_progress", "In progress"),
                            ("complete", "Completed"),
                            ("returned", "Returned"),
                            ("canceled", "Canceled"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("in_status_since", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("order_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("in_channel_id", models.PositiveIntegerField(null=True)),
                ("order_body", models.JSONField()),
                ("extra", models.JSONField(blank=True, default=dict, null=True)),
                ("preorder", models.BooleanField(default=False)),
                ("preorder_date", models.DateTimeField(blank=True, null=True)),
                ("pretty_id_snap", models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="django_checkout.cart"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_checkout.channel"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_accounts.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=6)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("additional_info", models.JSONField(blank=True, null=True)),
                ("preorder", models.BooleanField(default=False)),
                ("preorder_date", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_pim.product"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="django_checkout.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("invoice_number", models.CharField(blank=True, max_length=255, null=True)),
                ("invoice_base64", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice",
                        to="django_checkout.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="OrderAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="It will automatically be filled in with the file name when saving",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django_checkout.models.order_attachment.order_storage,
                        upload_to=django_checkout.models.order_attachment.order_directory_path,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="django_checkout.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderStatusLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("unpaid", "Unpaid"),
                            ("confirmed", "Confirmed"),
                            ("holded", "On hold"),
                            ("in_progress", "In progress"),
                            ("complete", "Completed"),
                            ("returned", "Returned"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name_t9n", models.JSONField(blank=True, null=True)),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("transfer", "Bank transfer"),
                            ("cod", "Cash on delivery"),
                            ("free_order", "Free order"),
                            ("payu", "PayU"),
                            ("payu_card", "PayU Card"),
                            ("payu_blik", "PayU BLIK"),
                            ("paypal", "PayPal"),
                            ("paynow", "PayNow"),
                            ("przelewy24", "Przelewy24"),
                            ("cash", "Cash"),
                            ("deferred_payment", "Deferred payment"),
                            ("autopay", "Autopay"),
                            ("stripe", "Stripe"),
                            ("voucher", "Voucher / Gift card"),
                        ],
                        default="transfer",
                        max_length=24,
                    ),
                ),
                ("is_cash_on_delivery", models.BooleanField(editable=False)),
                ("is_free_order", models.BooleanField(default=False, editable=False)),
                ("code", models.CharField(max_length=20)),
                ("image", models.ImageField(blank=True, null=True, upload_to="pic")),
                ("name_t9n", models.JSONField(blank=True, null=True)),
                ("description_t9n", models.JSONField(blank=True, null=True)),
                ("additional_data", models.JSONField(blank=True, null=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("without_fee", "Without Fee"),
                            ("flat_fee", "Flat Fee"),
                            ("percentage_fee", "Percentage Fee"),
                        ],
                        default="without_fee",
                        max_length=24,
                    ),
                ),
                (
                    "fee_value",
                    models.FloatField(
                        default=0.0,
                        help_text="Provide a percentage fee (e.g. 20.00) or flat fee value",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"),
                ),
                ("countries", models.ManyToManyField(to="django_regional.country")),
                ("currencies", models.ManyToManyField(to="django_regional.currency")),
                (
                    "customer_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group that can use this payment method. Leave blank to allow all users.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_accounts.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("approved", "Pending"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                ("external_order_id", models.CharField(blank=True, max_length=255, null=True)),
                ("redirect_url", models.TextField(blank=True, null=True)),
                ("provider_notify", models.JSONField(blank=True, null=True)),
                ("provider_request", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_items",
                        to="django_checkout.order",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_checkout.paymentmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductRepresentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(db_index=True, max_length=128)),
                ("origin_sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"),
                ),
            ],
            options={
                "verbose_name_plural": "products representations",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="SaleOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_checkout.productrepresentation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleOfferPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("price_from", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_to", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "country_code",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.currency"),
                ),
                (
                    "sale_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_offer_price",
                        to="django_checkout.saleoffer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("inpost", "Inpost"),
                            ("pickup_point", "Pickup Point"),
                            ("delivery", "Delivery"),
                            ("virtual", "Virtual"),
                        ],
                        default="default",
                        max_length=24,
                    ),
                ),
                ("dpm_code", models.JSONField(blank=True, null=True)),
                ("code", models.CharField(max_length=20)),
                ("image", models.ImageField(blank=True, null=True, upload_to="pic")),
                ("name_t9n", models.JSONField(blank=True, null=True)),
                ("description_t9n", models.JSONField(blank=True, null=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("matrix", "Matrix")], default="fixed", max_length=24
                    ),
                ),
                (
                    "max_weight",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "max_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum total volume for this shipping method.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20)),
                ("tracking_number", models.CharField(blank=True, max_length=255, null=True)),
                ("tracking_link", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_items",
                        to="django_checkout.order",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_checkout.shippingmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedProducts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(db_index=True, max_length=40)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "authentication_state",
                    models.CharField(
                        choices=[("all", "All"), ("guest", "Guest"), ("logged", "Logged")], default="all", max_length=24
                    ),
                ),
                (
                    "association_type",
                    models.CharField(
                        choices=[
                            ("sku", "Sku - in 'idx' field"),
                            ("category_idx", "Category idx - in 'idx' field"),
                            ("attribute_idx", "Attribute idx - in 'idx' field"),
                            ("attribute_value", "Attribute value - in 'idx' feature_idx, in 'value' attr value"),
                            ("product_class", "Product class (integer!)  - in 'idx' field"),
                            ("feature_set_idx", "Feature set idx - in 'idx' field"),
                        ],
                        default="sku",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_checkout.paymentmethod",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_checkout.shippingmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linked product",
                "verbose_name_plural": "Linked products",
            },
        ),
        migrations.CreateModel(
            name="LimitedProducts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(db_index=True, max_length=40)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "authentication_state",
                    models.CharField(
                        choices=[("all", "All"), ("guest", "Guest"), ("logged", "Logged")], default="all", max_length=24
                    ),
                ),
                (
                    "association_type",
                    models.CharField(
                        choices=[
                            ("sku", "Sku - in 'idx' field"),
                            ("category_idx", "Category idx - in 'idx' field"),
                            ("attribute_idx", "Attribute idx - in 'idx' field"),
                            ("attribute_value", "Attribute value - in 'idx' feature_idx, in 'value' attr value"),
                            ("product_class", "Product class (integer!)  - in 'idx' field"),
                            ("feature_set_idx", "Feature set idx - in 'idx' field"),
                        ],
                        default="sku",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_checkout.paymentmethod",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_checkout.shippingmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Limited product",
                "verbose_name_plural": "Limited products",
            },
        ),
        migrations.AddField(
            model_name="discountrulecode",
            name="free_shipping_methods",
            field=models.ManyToManyField(
                blank=True,
                help_text="Metody dostawy kwalifikujące się na darmową dostawę.",
                to="django_checkout.shippingmethod",
            ),
        ),
        migrations.CreateModel(
            name="ShippingOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country_code", models.CharField(default="ALL", max_length=10)),
                ("tax_rate", models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ("price_brutto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                (
                    "free_delivery_above_brutto",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("cash_on_delivery_available", models.BooleanField(default=False)),
                (
                    "cash_on_delivery_fee",
                    models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="django_regional.country"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_regional.currency"),
                ),
                (
                    "method",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.shippingmethod"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_items",
                        to="django_checkout.order",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_checkout.shippingoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingPriceMatrix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "filter_type",
                    models.CharField(choices=[("all", "ALL"), ("attr", "ATTR")], default="all", max_length=24),
                ),
                (
                    "free_delivery_above_brutto",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("idx", models.CharField(blank=True, max_length=256, null=True)),
                ("value", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "shipping_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_price_matrixes",
                        to="django_checkout.shippingoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Price Matrix",
                "verbose_name_plural": "Shipping Price Matrixes",
                "ordering": ["shipping_option", "filter_type"],
            },
        ),
        migrations.CreateModel(
            name="ShippingPriceByWeight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ("price_brutto", models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                (
                    "shipping_price_matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_price_option_matrix",
                        to="django_checkout.shippingpricematrix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Price By Weight",
                "verbose_name_plural": "Shipping Prices By Weight",
            },
        ),
        migrations.CreateModel(
            name="SplitOrderLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "split_order_mechanism",
                    models.CharField(
                        choices=[("MODIFY_AND_CREATE", "Modify original order and create new needed orders")],
                        default="MODIFY_AND_CREATE",
                        max_length=45,
                    ),
                ),
                ("split_by_feature_idx", models.CharField(max_length=100)),
                ("split_by_attribute_value", models.CharField(max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="django_checkout.channel"
                    ),
                ),
                (
                    "original_cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="original_cart_link",
                        to="django_checkout.cart",
                    ),
                ),
                (
                    "original_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="original_order",
                        to="django_checkout.order",
                    ),
                ),
                (
                    "split_cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="split_cart",
                        to="django_checkout.cart",
                    ),
                ),
                (
                    "split_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="split_order",
                        to="django_checkout.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Split Order Link",
                "verbose_name_plural": "Split Order Links",
                "db_table": "split_order_link",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="split_orders",
            field=models.ManyToManyField(through="django_checkout.SplitOrderLink", to="django_checkout.order"),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=0)),
                ("saleable_quantity_limit_per_order", models.IntegerField(default=999999)),
                ("saleable_quantity_limit", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_checkout.productrepresentation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reserved_quantity", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.order")),
                ("stock", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.stock")),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=254)),
                ("name", models.CharField(max_length=254)),
                ("is_global", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_suppliers",
                        to="django_checkout.channel",
                        verbose_name="channel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stock",
            name="supplier",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.supplier"),
        ),
        migrations.CreateModel(
            name="SupplierCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_suppliers",
                        to="django_accounts.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_customers",
                        to="django_checkout.supplier",
                        verbose_name="supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThresholdProductFilter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("take_common_part", models.BooleanField(default=False)),
                ("product_price_to", models.PositiveIntegerField(blank=True, null=True)),
                ("product_price_from", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_price_to", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_price_from", models.PositiveIntegerField(blank=True, null=True)),
                ("qty_to", models.PositiveIntegerField(blank=True, null=True)),
                ("qty_from", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_qty_to", models.PositiveIntegerField(blank=True, null=True)),
                ("cart_qty_from", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_inclusion_or_exclusion",
                    models.CharField(
                        choices=[
                            ("inclusion", "Includes all products with specific parameters."),
                            ("exclusion", "Excludes all products with specific parameters."),
                        ],
                        default="inclusion",
                        max_length=256,
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(blank=True, related_name="%(class)s_attributes", to="django_pim.attribute"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_categories", to="django_pim.productcategory"
                    ),
                ),
                (
                    "features_qty_greater_than_attr_value",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Include or exclude product which have product attribute associated with the given feature and if the quantity of the product in the cart exceeds the value of this attribute.",
                        related_name="%(class)s_features_qty_greater_than_attr_value",
                        to="django_pim.feature",
                    ),
                ),
                (
                    "features_qty_is_multiple_of_attr_value",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Include or exclude product which have product attribute associated with the given feature and if the quantity of the product in the cart is a multiple of the value of this attribute.",
                        related_name="%(class)s_features_qty_is_multiple_of_attr_value",
                        to="django_pim.feature",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If you pick product configurable all child will be excluded/included",
                        related_name="%(class)s_products",
                        to="django_pim.product",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threshold_filters",
                        to="django_checkout.discountrulecode",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UsedCoupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "shipping_email",
                    models.EmailField(db_index=True, help_text="Email z shipping address", max_length=254),
                ),
                (
                    "billing_email",
                    models.EmailField(db_index=True, help_text="Email z billing address", max_length=254),
                ),
                ("discount_code", models.CharField(db_index=True, max_length=255)),
                (
                    "channel",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_checkout.channel"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_accounts.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_coupons",
                        to="django_checkout.order",
                    ),
                ),
            ],
            options={
                "db_table": "django_checkout_used_coupon",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(fields=("cart_id",), name="unique_cart_id"),
        ),
        migrations.AlterUniqueTogether(
            name="customsthresholdconfig",
            unique_together={("country",)},
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["rule", "code"], name="idx_dc_rule_code"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["rule", "active_from", "active_to"], name="idx_dc_dates"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["rule", "max_products_qty"], name="idx_dc_max_qty"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["rule", "current_used", "max_used"], name="idx_dc_usage"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["code"], name="idx_dc_code"),
        ),
        migrations.AddConstraint(
            model_name="discountcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_used__lte", models.F("max_used"))),
                name="current_used_lesser_than_or_equal_to_max_used",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountcode",
            constraint=models.CheckConstraint(
                condition=models.Q(("active_to__gte", models.F("active_from"))),
                name="check_active_to_greater_than_active_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderstatuslabel",
            constraint=models.UniqueConstraint(fields=("channel", "status"), name="one_label_per_channel"),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                fields=("channel", "code"), name="unique_payment_method_code_per_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_cash_on_delivery", True), ("provider", "cod")),
                fields=("channel",),
                name="unique_cod_payment_per_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_cash_on_delivery", True), ("provider", "cod")),
                    ("is_cash_on_delivery", False),
                    _connector="OR",
                ),
                name="provider_cod_or_is_cash_on_delivery_false",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_free_order", True), ("provider", "free_order")),
                fields=("channel",),
                name="unique_free_order_payment_per_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_free_order", True), ("provider", "free_order")),
                    ("is_free_order", False),
                    _connector="OR",
                ),
                name="provider_free_order_or_is_free_order_false",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(fields=("order", "code"), name="one_intent_per_order_code"),
        ),
        migrations.AddConstraint(
            model_name="productrepresentation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("sku"),
                models.F("channel"),
                name="unique_checkout_product_sku_in_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleoffer",
            constraint=models.UniqueConstraint(fields=("product",), name="unique_sale_offer_per_product"),
        ),
        migrations.AlterUniqueTogether(
            name="saleofferprice",
            unique_together={("sale_offer", "currency", "country_code")},
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.UniqueConstraint(
                fields=("channel", "code"), name="unique_shipping_method_code_per_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingintent",
            constraint=models.UniqueConstraint(fields=("order",), name="one_shipping_intent_per_order"),
        ),
        migrations.AddIndex(
            model_name="linkedproducts",
            index=models.Index(
                fields=["is_active", "shipping_method", "payment_method", "authentication_state", "association_type"],
                name="idx_linkedproducts_combo",
            ),
        ),
        migrations.AddConstraint(
            model_name="linkedproducts",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("payment_method__isnull", True), ("shipping_method__isnull", False)),
                    models.Q(("payment_method__isnull", False), ("shipping_method__isnull", True)),
                    _connector="OR",
                ),
                name="linked_product_check",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="linkedproducts",
            unique_together={
                ("idx", "value", "payment_method", "association_type"),
                ("idx", "value", "shipping_method", "association_type"),
            },
        ),
        migrations.AddIndex(
            model_name="limitedproducts",
            index=models.Index(
                fields=["is_active", "shipping_method", "payment_method", "authentication_state", "association_type"],
                name="idx_limitedproducts_combo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="limitedproducts",
            unique_together={
                ("idx", "value", "payment_method", "association_type"),
                ("idx", "value", "shipping_method", "association_type"),
            },
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(("modifier", "percent_discount"), ("extra_value__gt", 0), _connector="OR"),
                name="check_extra_value_positive_int_percent_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(("modifier", "price_discount"), ("extra_value__gt", 0), _connector="OR"),
                name="check_extra_value_positive_int_price_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modifier", "step_qty_percent_discount"), ("extra_value__isnull", False), _connector="OR"
                ),
                name="check_extra_value_not_empty_dict_step_qty_percent_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modifier", "step_price_percent_discount"), ("extra_value__isnull", False), _connector="OR"
                ),
                name="check_extra_value_not_empty_dict_step_price_percent_discount",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modifier", "step_qty_fixed_price_per_currency"), ("extra_value__isnull", False), _connector="OR"
                ),
                name="check_extra_value_not_empty_dict_step_qty_fixed_price_per_currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(("modifier", "cheapest_gratis"), ("extra_value__gt", 0), _connector="OR"),
                name="check_extra_value_positive_int_cheapest_gratis",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(("modifier", "most_expensive_gratis"), ("extra_value__gt", 0), _connector="OR"),
                name="check_extra_value_positive_int_most_expensive",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(("modifier", "gratis_stepped"), ("extra_value__isnull", False), _connector="OR"),
                name="check_extra_value_not_empty_dict_gratis_stepped",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrulecode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modifier", "gratis_by_sku_in_cart"), ("extra_value__isnull", False), _connector="OR"
                ),
                name="check_extra_value_not_empty_list_gratis_by_sku_in_cart",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingoption",
            constraint=models.UniqueConstraint(
                fields=("method", "country_code", "currency"), name="one_currency_per_country_per_method"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("country__isnull", True), ("country_code", "FAKE")),
                    models.Q(("country__isnull", True), ("country_code", "ALL")),
                    ("country__isnull", False),
                    _connector="OR",
                ),
                name="has_country_or_avaliable_for_all",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingoption",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cash_on_delivery_available", False), ("cash_on_delivery_fee__isnull", True)),
                    models.Q(("cash_on_delivery_available", True), ("cash_on_delivery_fee__isnull", False)),
                    _connector="OR",
                ),
                name="cod_available_or_cod_extra_isnull",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipping",
            constraint=models.UniqueConstraint(fields=("order",), name="one_shipping_per_order"),
        ),
        migrations.AddConstraint(
            model_name="shippingpricematrix",
            constraint=models.UniqueConstraint(
                fields=("shipping_option", "filter_type", "idx", "value"), name="unique_shipping_price_matrix"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingpricebyweight",
            constraint=models.UniqueConstraint(
                fields=("shipping_price_matrix", "weight"), name="unique_shipping_price_by_weight"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="splitorderlink",
            unique_together={("original_cart", "split_by_feature_idx", "split_by_attribute_value")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["channel", "billing_email", "order_status"], name="idx_order_billing_email"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["channel", "shipping_email", "order_status"], name="idx_order_shipping_email"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(fields=("cart",), name="one_cart_per_order"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(fields=("order_id",), name="unique_order_id"),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("in_channel_id__isnull", False)),
                fields=("channel", "in_channel_id"),
                name="in_channel_id_unique_per_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_global", True)), fields=("channel",), name="unique_supplier_global_per_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="usedcoupon",
            index=models.Index(fields=["channel", "billing_email", "discount_code"], name="idx_used_coupon_billing"),
        ),
        migrations.AddIndex(
            model_name="usedcoupon",
            index=models.Index(fields=["channel", "shipping_email", "discount_code"], name="idx_used_coupon_shipping"),
        ),
        migrations.AddIndex(
            model_name="usedcoupon",
            index=models.Index(fields=["channel", "customer", "discount_code"], name="idx_used_coupon_customer"),
        ),
    ]
